import Vue from 'vue'

import { Tabbar, TabbarItem, Loading, Grid, GridItem, CountDown, Lazyload, Tab, Tabs,
  Divider, Toast, NavBar, SubmitBar, Checkbox, CheckboxGroup, Dialog, Cell, CellGroup, 
  Tag, ContactCard, ContactList, ContactEdit, Icon, RadioGroup, Radio, Switch, Field, 
  AddressList, AddressEdit, Area, Popup, SwipeCell, Button, DatetimePicker, CouponCell, 
  CouponList, Sticky, Sidebar, SidebarItem, GoodsAction, GoodsActionIcon, GoodsActionButton,
  Overlay } from 'vant'
Vue.use(Tabbar)
.use(TabbarItem)
.use(Loading)
.use(Grid)
.use(GridItem)
.use(CountDown)
.use(Lazyload)
.use(Tab)
.use(Tabs)
.use(Divider)
.use(Toast)
.use(NavBar)
.use(SubmitBar)
.use(Checkbox)
.use(CheckboxGroup)
.use(Dialog)
.use(Cell)
.use(CellGroup)
.use(Tag)
.use(ContactCard)
.use(ContactList)
.use(ContactEdit)
.use(Icon)
.use(RadioGroup)
.use(Radio)
.use(Switch)
.use(Field)
.use(AddressList)
.use(AddressEdit)
.use(Area)
.use(Popup)
.use(SwipeCell)
.use(Button)
.use(DatetimePicker)
.use(CouponCell)
.use(CouponList)
.use(Sticky)
.use(Sidebar)
.use(SidebarItem)
.use(GoodsAction)
.use(GoodsActionIcon)
.use(GoodsActionButton)
.use(Overlay)

